name: ezzypolls
services:
  db:
    container_name: ezzypollsdb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ezzypolls
      POSTGRES_PASSWORD: password
    ports:
      - '5500:5432'
    volumes:
      - ezzypollsdata:/var/lib/postgresql/data

volumes:
  ezzypollsdata:
